FROM python:3.14-slim-trixie
WORKDIR /app
RUN pip install uv
# (1) les dépendances seules : la couche lourde
COPY pyproject.toml uv.lock README.md ./
RUN uv sync --locked --no-install-project
# (2) le code, puis le projet
COPY src ./src
RUN uv sync --locked
