name : CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
            - name: installer uv
              uses: astral-sh/setup-uv@v10.0.1
              with:
                enable-cache: true
            - name: Installer les dépendances
              run: uv sync
            - name: Vérifier le formatage
              run: uv run ruff format --check .
            - name: Linter le code
              run: uv run ruff check .
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
            - name: installer uv
              uses: astral-sh/setup-uv@v10.0.1        
              with:
                enable-cache: true
            - name: Installer les dépendances
              run: uv sync

            - name: Lancer les tests
              run: uv run pytest -v
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v7
          - name: Installer uv
            uses: astral-sh/setup-uv@v10.0.1
            with:
              enable-cache: true
          - name: Installer les dépendances
            run: uv sync
          - name: Construire le paquet
            run: uv build