name : CI

on:
  push:
    branches:
      - main

  pull_request:

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
permissions: {}
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
            - uses: ./.github/actions/setup
            - name: Vérifier le formatage
              run: uv run ruff format --check .
            - name: vérifier le lint
              run: uv run ruff check .
    test:
        runs-on: ubuntu-latest
        strategy:
          fail-fast: false
          matrix:
            python-version: [3.12, 3.13,3.14]

        steps:
            - uses: actions/checkout@v7
            - uses: ./.github/actions/setup
              with:
               python-version: ${{ matrix.python-version }}

            - name: Lancer les tests
              run: uv run pytest -v --cov=. --cov-report=html
            - name: Publier le rapport de couverture
              uses: actions/upload-artifact@v7
              with:
                name: coverage-html-${{ matrix.python-version }}
                path: htmlcov/
                retention-days: 7

    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v7
          - uses: ./.github/actions/setup
          - name: Construire le paquet
            run: uv build
